spring:
  application:
    name: gamerec-server
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

igdb:
  client-id: ${IGDB_CLIENT_ID:}
  client-secret: ${IGDB_CLIENT_SECRET:}
  base-url: https://api.igdb.com/v4
  token-url: https://id.twitch.tv/oauth2/token

game-cache:
  ttl-days: 7
